Vagrant.configure("2") do |config|

  (1..5).each do |i|
    config.vm.define "vm#{10 + i}" do |node|
      node.vm.box = "centos/8"
      node.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "vm#{10 + i}"
        vb.memory = "2048"
        vb.cpus = 1
      end
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end

end

