Vagrant.configure("2") do |config|

  (1..6).each do |i|
    config.vm.define "vm#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.network "private_network", ip: "192.168.56.#{i + 1}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "vm#{i}"
        vb.memory = "2048"
        vb.cpus = 1
      end
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end

end


